### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by Belobobr** [hungdev/react-native-alias-example#1]
<img width="314" alt="screen shot 2019-01-24 at 15 34 17" src="https://user-images.githubusercontent.com/5969678/51678481-950edc00-1fed-11e9-96c3-b095ea3cce50.png">

**Comment by hungdev** [comment]
@Belobobr hi guy. The first time I also had errors like you. After that, i realized that config is not be allowed to import in root tree (same level with package.json). [like this](https://github.com/hungdev/react-native-alias-example/blob/master/App.js#L11)
You can only import it in the folder. See more my example.

**Comment by hungdev** [comment]
Now it worked
